/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useLoader } from '@react-three/fiber';
import { TextureLoader } from 'three';
import { useGLTF, useTexture } from "@react-three/drei";
import React, { useEffect } from "react";
import {motion} from "framer-motion-3d"
import { useRef } from 'react';


import * as THREE from "three";
import { animate, useMotionValue } from "framer-motion";
import { useFrame } from "@react-three/fiber";
import { Avatar } from './Avatar'
import { Text } from 'troika-three-text';
import { extend } from '@react-three/fiber';
extend({ Text });

export function Office(props) {
  const {section} = props;
  const { nodes: bookshelfNodes, materials: bookshelfMaterials } = useGLTF('textures/bookshelf.glb');
  const quadroTexture = useLoader(TextureLoader, 'textures/quadrotext.jpg');
  const quadroMaterial = new THREE.MeshStandardMaterial({
    map: quadroTexture,
    transparent: true,
    opacity: 1, // Ajuste a opacidade conforme necessário
  });
  
  const { nodes, materials } = useGLTF("models/scene.gltf");
  const texture = useTexture("textures/baked.jpg");
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1,
  });


useEffect(() => {
  if (quadroTexture) {
    // Rodar a textura em 90 graus
    quadroTexture.center.set(0.5, 0.5); // Define o ponto central para a rotação
    quadroTexture.rotation = Math.PI / -2; // 90 graus em radianos

    // Ajustes adicionais, se necessário
    quadroTexture.wrapS = THREE.RepeatWrapping;
    quadroTexture.wrapT = THREE.RepeatWrapping;
    quadroTexture.repeat.set(9, 13);
  }
}, [quadroTexture]);


  return (
    <group {...props} dispose={null}>
      <group
        name="Desk"
        position={[-0.07, 0, -1.52]}
        rotation={[0, -Math.PI / 2, 0]}
      >
        <mesh
          name="Plane001_Plane002_BlackWood001"
          geometry={nodes.Plane001_Plane002_BlackWood001.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plane001_Plane002_BlackWood001_1"
          geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plane001_Plane002_BlackWood001_2"
          geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plane001_Plane002_BlackWood001_3"
          geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plane001_Plane002_BlackWood001_4"
          geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry}
          material={textureMaterial}
        />
      </group>
      <group name="SM_ShelfSM_Shelf1" position={[-0.87, 1.69, -2.04]}>
        <mesh
          name="SM_ShelfSM_Shelf1_1"
          geometry={nodes.SM_ShelfSM_Shelf1_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="SM_ShelfSM_Shelf1_1_1"
          geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry}
          material={textureMaterial}
        />
      </group>
      <motion.group 
      scale={[0, 0, 0]}
      animate={{
        scale: section === 0 ? 1 : 0,
      }}
      name="LavaLamp" 
      position={[-1.3, 2.07, -1.99]}
      
      >
        <mesh
          name="Node-Mesh001"
          geometry={nodes["Node-Mesh001"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh001_1"
          geometry={nodes["Node-Mesh001_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh001_2"
          geometry={nodes["Node-Mesh001_2"].geometry}
          material={textureMaterial}
        />
      </motion.group>
      <motion.mesh 
      scale={[0, 0, 0]}
      animate={{
        scale: section === 0 ? 1 : 0,
      }}
        name="WawaRug"
        geometry={nodes.WawaRug.geometry}
        material={textureMaterial}
        position={[-0.28, 0.01, 0.76]}
      />
      <motion.group 
      scale={[0, 0, 0]}
      animate={{
        scale: section === 0 ? 1 : 0,
      }}
        name="salameche"
        position={[-0.61, 2.04, -1.96]}
        rotation={[-Math.PI, 0.73, -Math.PI]}
      >
        <mesh
          name="mesh434900071"
          geometry={nodes.mesh434900071.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh434900071_1"
          geometry={nodes.mesh434900071_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh434900071_2"
          geometry={nodes.mesh434900071_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh434900071_3"
          geometry={nodes.mesh434900071_3.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh434900071_4"
          geometry={nodes.mesh434900071_4.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh434900071_5"
          geometry={nodes.mesh434900071_5.geometry}
          material={textureMaterial}
        />
      </motion.group>
      <group
        name="keyboard"
        position={[-0.04, 0.98, -1.55]}
        rotation={[0, -0.17, 0]}
      >
        <mesh
          name="mesh425587018"
          geometry={nodes.mesh425587018.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh425587018_1"
          geometry={nodes.mesh425587018_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh425587018_2"
          geometry={nodes.mesh425587018_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh425587018_3"
          geometry={nodes.mesh425587018_3.geometry}
          material={textureMaterial}
        />
      </group>
      <group
        name="iMac"
        position={[0.45, 0.94, -1.72]}
        rotation={[Math.PI, -1.1, Math.PI]}
      >
                
        <mesh
          name="iMac_1"
          geometry={nodes.iMac_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="iMac_1_1"
          geometry={nodes.iMac_1_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="iMac_1_2"
          geometry={nodes.iMac_1_2.geometry}
          material={textureMaterial}
        />
      </group>
      <mesh
        name="Comp_Mouse"
        geometry={nodes.Comp_Mouse.geometry}
        material={textureMaterial}
      />
      <motion.group 
      scale={[0, 0, 0]}
      animate={{
        scale: section === 0 ? 1 : 0,
      }} name="plant" position={[-0.78, 1.07, -1.61]}>
        <mesh
          name="mesh24448074"
          geometry={nodes.mesh24448074.geometry}
          material={textureMaterial}
        />
        
        <mesh
          name="mesh24448074_1"
          geometry={nodes.mesh24448074_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh24448074_2"
          geometry={nodes.mesh24448074_2.geometry}
          material={textureMaterial}
        />
      </motion.group>
      <motion.group 
      scale={[0, 0, 0]}
      animate={{
        scale: section === 0 ? 1 : 0,
      }}
        name="Houseplant_7"
        position={[-2.02, -0.04, -1.53]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          name="Houseplant_7_1"
          geometry={nodes.Houseplant_7_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Houseplant_7_2"
          geometry={nodes.Houseplant_7_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Houseplant_7_3"
          geometry={nodes.Houseplant_7_3.geometry}
          material={textureMaterial}
        />
      </motion.group>
      <motion.group 
        name="bookshelf"
        position={[1, 2, -1.06]} // Ajuste a posição conforme necessário
        rotation={[-Math.PI, 0.67, -Math.PI]} // Ajuste a rotação conforme necessário
        scale={[0.06, 1, 0.5]} // Ajuste a escala conforme necessário
      >
        <mesh
          castShadow
          receiveShadow
          geometry={bookshelfNodes.Object_4.geometry}
          material={bookshelfMaterials.Bookshelf}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={bookshelfNodes.Object_5.geometry}
          material={bookshelfMaterials.Book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={bookshelfNodes.Object_6.geometry}
          material={bookshelfMaterials.Book}
        />
      </motion.group>
      <motion.group 
      scale={[0, 0, 0]}
      animate={{
        scale: section === 0 ? 1 : 0,
      }} name="Chair" position={[-0.28, 0, -0.71]} rotation={[0, -0.38, 0]}>
        
        <mesh
          name="Node-Mesh"
          geometry={nodes["Node-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh_1"
          geometry={nodes["Node-Mesh_1"].geometry}
          material={textureMaterial}
        />
      </motion.group>
      <Avatar 
        position={[-0.2, 0.4, -0.47]} 
        rotation={[-1.7, 0.1, 3]} 
        scale={[-1, 1, 1]} 
        animation="Typing" 
      />
      <mesh
        name="Plane001"
        geometry={nodes.Plane001.geometry}
        material={textureMaterial}
      />
      <mesh
        name="Plane001_1"
        geometry={nodes.Plane001_1.geometry}
        material={textureMaterial}
      />
      <mesh
        name="Plane001_2"
        geometry={nodes.Plane001_2.geometry}
        material={textureMaterial}
      />
      <mesh
        name="Plane001_3"
        geometry={nodes.Plane001_3.geometry}
        material={quadroMaterial}
        onClick={() => window.location.href = 'https://seusite.com/projetos'}
        >
        {/* Se o quadro tiver alguma animação ou características especiais, adicione aqui */}
      </mesh>
    </group>
  );
}

useGLTF.preload("models/scene.gltf");
useGLTF.preload('textures/bookshelf.glb');

